### PR TITLE
Spanish

### PR DESCRIPTION
**Pull request by marcoachury**
Translated strings to spanish. 

Please check.
I have some doubts about style, but the strings are usable.

Best regards

Marco Achury

### CODE REVIEW

**Comment by gonzamontiel** [comment]
Hola Marco! 
As a dev at SatoshiPay and occasional contributor to solar, I reviewed the branch and took the liberty of modifying some strings. I was trying to add a commit with these changes to your branch in order to approve the pull request, but GitHub gives us a _permission denied_ error; can you grant us access to push to your branch?  Thanks!

**Comment by marcoachury** [comment]
> 
> 
> Hola Marco!
> As a dev at SatoshiPay and occasional contributor to solar, I reviewed the branch and took the liberty of modifying some strings. I was trying to add a commit with these changes to your branch in order to approve the pull request, but GitHub gives us a _permission denied_ error; can you grant us access to push to your branch? Thanks!

Not sure what to do.  I think the owner of solar must to approve.  Check in the image the message on my github session.

imagen

**Comment by andywer** [comment]
@marcoachury Thanks a lot for your contribution! What @gonzamontiel meant is the ["Allow edits from maintainers" option](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests).

Usually this is set, so that we can do modifications to proposed changes. There was an error when we tried to edit your PR, so we guess this option might not be checked. Would make things easier for us if that setting was set. Otherwise we might need to close this PR and open a new one with the updated proposal.

**Comment by marcoachury** [comment]
I am not sure.

Note the option is set.   I am not expert using GIT.  May be the error is because I merged to master branch on my local repository? When I did the pull request, GITHUB tried to send it to master branch?


imagen

**Comment by gonzamontiel** [comment]
Thanks Marco! I was able to push the changes to the branch, I don't know what was happening before.

**Comment by marcoachury** [comment]
A stylish clarification.  I have a comment about translate the term "Cancel" to spanish.  On Windows is usual that the term is translate as "Cancelar" to abort any process.   But in some contexts "Cancelar" means to pay or to settle a debt.  On a program about finance the term may be confusing.  This is why I left "Anular", inspired on the italian translate.  This word may be adjust better to the concept of abort a process.

**Comment by gonzamontiel** [comment]
>  But in some contexts "Cancelar" means to pay or to settle a debt. 

Hi Marco, I see your point. In general, I think _cancelar_ would suffice and is more widely used than _anular_, but I know in some countries the use of _cancelar_ as paying is almost a normal thing. **I then agree with you** , and we can keep _anular_, could you please put back those cases? Then I think we can approve the PR if you're also okay with the rest.

**Comment by andywer** [comment]
@gonzamontiel Is that ready to be merged?

**Comment by gonzamontiel** [comment]
> @gonzamontiel Is that ready to be merged?

I think it is.

**Comment by marcoachury** [comment]
I really had not time last weeks to check this.  Gonzalo did corrections that looks well.  Will be great to have it on next release.

**Pull request merged**
