### PR TITLE
Feature/403 add icons and splashscreen

### PR DESCRIPTION
**Pull request by Marcel-Ebert**
Adds resources for launcher icons and splash screens and configures cordova builds to use them.

### CODE REVIEW

**Comment by andywer** [comment]
@Marcel-Ebert Is it really necessary to check the cordova plugins' code into our git repository? They should rather be git-ignored and installed by some package manager.

**Comment by Marcel-Ebert** [comment]
@andywer It won't be necessary if we go ahead and remove the platform specific code as we discussed earlier today.
I will take care of it soon.

**Comment by andywer** [comment]
Ahh, alright. But then let's look into that before we merge this PR 😉

**Comment by andywer** [comment]
Needs to be rebased (merging `feature/cordova` back into the feature branch is fine, too).

**Comment by andywer** [comment]
Let's get this merged. Created #453 as a follow-up.

**Pull request merged**
