### PR TITLE
Put fingerprint lock behind feature flag

### PR DESCRIPTION
**Pull request by andywer**
Default is off.

@Marcel-Ebert Can you please try on Android? I don't expect any surprises there, but just to be safe 😉

### CODE REVIEW

**Comment by Marcel-Ebert** [comment]
I tested it on android and it does work overall, BUT I found a scenario where the application stops working:
Launch the app without fingerprint lock enabled, go to settings, turn on fingerprint lock, leave the application (press home), then reenter the application and it does not respond anymore. 
I tried capturing log statements but no error messages are shown.

@andywer maybe you have any idea why this could happen? It does not occur the other way around and it will work as expected when completely shutting down the app.

**Comment by andywer** [comment]
@Marcel-Ebert i think i know why! in `app.cordova.ts` the client secret promise will not have been set yet...

**Comment by andywer** [comment]
@Marcel-Ebert Can you try again, pls?

**Comment by Marcel-Ebert** [comment]
Tested it on physical device and emulator and is working as expected now. 👍

**Pull request merged**
