### PR TITLE
Support StellarGuard setup via SEP-7 request

### PR DESCRIPTION
**Pull request by ebma**
- [x] Create `transactionRequest` context which receives the `web+stellar` request and parses+verifies URIs
- [x] Create `TransactionRequestHandler` which renders a component based on the Transaction URI
- [x] Create `StellarGuardActivationDialog` 
- [x] Add `stellar-uri` dependency for URI parsing (+ `babel-polyfill` dependency because `stellar-uri` doesn't compile without it)
- [x] Add button to create a new account to `AccountSelectionList` component
- [x] Add function that creates a copy of a `Transaction` but replaces the source account to `lib/transaction.ts` (needed in `StellarGuardActivation` to replace the source account from the transaction contained in the SEP-0007 transaction with the account that was selected by the user)
- [x] Add `account` to `sendTransaction()` signature  and remove the `account` prop from `TransactionSender` to support sending transactions in cases where the sending account is unknown at first

### CODE REVIEW

**Comment by Marcel-Ebert** [comment]
Sample SEP-0007 URI for testing purposes:
`
web+stellar:tx?xdr=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAyAAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAF05w34AAAAAAAAAAgAAAAAAAAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAKpyKlEEkhH52s93pdj8brKxBqNa5rVLApMCt2JtYQhqAAAAAQAAAAAAAAAFAAAAAAAAAAAAAAAAAAAAAQAAAAoAAAABAAAAFAAAAAEAAAAUAAAAAQAAABQAAAAAAAAAAQAAAADI1z%2BaQbFMn2HwYjtas1m2CyjAEEvhBAxPY2Iy61I6iwAAAAoAAAAAAAAAAA%3D%3D&origin_domain=test.stellarguard.me&network_passphrase=Test+SDF+Network+%3B+September+2015
`

**Comment by naeim249** [comment]
#659

**Comment by andywer** [comment]
@naeim249 Are you trying to tell us something? 😉
(The linked issue doesn't seem to be related to this PR at all, though)

**Comment by andywer** [comment]
Let's close this PR for now, but use it as a reference for the new PR you are working on, @ebma

**Pull request closed without merging**
